### ISSUE TITLE
Retry message consume on worker thread interrupt

### ISSUE THREAD

**Issue by rohitsanj** [confluentinc/ide-sidecar#185]
Saw this when testing message viewer using sidecar v0.79.0. Unsure what the root cause for the interrupt was, but we should handle this case especially for the message consume API.

```
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1133)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:63)
        ... 40 more
```

Full stack trace:
```
 java.lang.RuntimeException: Failed to deserialize record
        at io.confluent.idesidecar.restapi.messageviewer.RecordDeserializer.deserialize(RecordDeserializer.java:286)
        at io.confluent.idesidecar.restapi.messageviewer.RecordDeserializer_ClientProxy.deserialize(Unknown Source)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.deserialize(ConfluentCloudConsumeStrategy.java:244)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.lambda$processPartition$3(ConfluentCloudConsumeStrategy.java:196)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
      va.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.processPartition(ConfluentCloudConsumeStrategy.java:216)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.lambda$decodeSchemaEncodedValues$2(ConfluentCloudConsumeStrategy.java:163)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.decodeSchemaEncodedValues(ConfluentCloudConsumeStrategy.java:164)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.postProcess(ConfluentCloudConsumeStrategy.java:105)
        at io.confluent.idesidecar.restapi.messageviewer.strategy.ConfluentCloudConsumeStrategy.lambda$execute$0(ConfluentCloudConsumeStrategy.java:72)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.CompletionException: java.lang.InterruptedException
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.confluent.idesidecar.restapi.messageviewer.RecordDeserializer.deserialize(RecordDeserializer.java:256)
        ... 38 more
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1133)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:63)
        ... 40 more

```

**Comment by rohitsanj** [comment]
We saw this issue in an integration test running in Semaphore CI - https://semaphore.ci.confluent.io/jobs/f3dda7e5-e35a-4d84-9c4b-e8171cce8848/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902&test_id=8cfb673c-b0e4-3a40-9746-b741185d43ff

**Comment by rohitsanj** [comment]
Hm, I believe it's due to this [`.await()`](https://github.com/confluentinc/ide-sidecar/blob/f71a45262257cbca7b5722ec211ded14e96afd31/src/main/java/io/confluent/idesidecar/restapi/messageviewer/RecordDeserializer.java#L255) call in `RecordDeserializer`.

**Comment by flippingbits** [comment]
Haven't seen this error for quite some time. Closing for now. Let's reopen the issue if we ever run into it again.
